# Generated by Django 5.2.4 on 2025-08-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_genie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberCorrect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('wrong', models.IntegerField(default=0)),
                ('date', models.DateField(unique=True)),
            ],
        ),
    ]
